services:
  backend:
    container_name: backend
    build:
      context: ./backend
    profiles:
      - prod
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCRAPER_API_PORT: ${SCRAPER_API_PORT}
      SCRAPER_API_HOST: ${SCRAPER_API_HOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_SCRAPER_CAR_MAKE_QUEUE_NAME: ${RABBITMQ_SCRAPER_CAR_MAKE_QUEUE_NAME}
      RABBITMQ_SCRAPER_CAR_MODEL_QUEUE_NAME: ${RABBITMQ_SCRAPER_CAR_MODEL_QUEUE_NAME}
    networks:
      - default
    healthcheck:
      test: "curl --fail --silent ${BACKEND_HOST}:${BACKEND_PORT}/api/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  scrapperApi:
    container_name: carlog-scrapper-api
    image: carlog-scrapper-api
    build: ./scrapperApi
    ports:
      - "9001:9001"
    depends_on:
      - rabbitmq
    environment:
      SCRAPER_API_PORT: ${SCRAPER_API_PORT}
      SCRAPER_CAR_MAKES_URL: ${SCRAPER_CAR_MAKES_URL}
      SCRAPER_CAR_MAKE_MODELS_BASE_URL: ${SCRAPER_CAR_MAKE_MODELS_BASE_URL}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      RABBITMQ_SCRAPER_CAR_MAKE_QUEUE_NAME: ${RABBITMQ_SCRAPER_CAR_MAKE_QUEUE_NAME}
      RABBITMQ_SCRAPER_CAR_MODEL_QUEUE_NAME: ${RABBITMQ_SCRAPER_CAR_MODEL_QUEUE_NAME}
      CHROME_EXECUTABLE_PATH: ${CHROME_EXECUTABLE_PATH}

  db:
    image: postgres:15
    container_name: carlog-db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - default
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - default
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  db-data:
  backend-build:
  scrapper-build:
  rabbitmq-data:

networks:
  default:
    name: carlog_network
    driver: bridge

